log:
  level: debug
  file: "/var/log/mosdns.log"
data_providers:
  - tag: cn_domain
    file: accelerated-domains.china.conf.raw.txt
    auto_reload: true
  - tag: apple_domain
    file: apple.china.conf.raw.txt
    auto_reload: true

plugins:
  #  - tag: _default_cache
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "tls://1.12.12.12"
          enable_pipeline: true
        - addr: "tls://120.53.53.53"
          enable_pipeline: true
        - addr: "tls://223.5.5.5"
          enable_pipeline: true
        - addr: "tls://223.6.6.6"
          enable_pipeline: true
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: "https://8.8.8.8/dns-query"
          dial_addr: "8.8.8.8"
          enable_http3: true
        - addr: "https://8.8.4.4/dns-query"
          dial_addr: "8.8.4.4"
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "104.16.249.249"
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "104.16.248.249"
          enable_http3: true

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:cn_domain"
        - "provider:apple_domain"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        # - _default_cache
        - if: query_is_local_domain
          exec:
            - _prefer_ipv4
            - forward_local
            - _return
          else_exec:
            - _prefer_ipv4
            - forward_remote

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":53"
      - protocol: tcp
        addr: ":53"

api:
  http: ":8000"
