server_addr: ':53'
debug: true
blacklist_domain:
  - 'anti-ad-domains.txt'
local_upstream:
  - 'tls://223.5.5.5'
  - 'tls://223.6.6.6'
  - 'tls://1.12.12.12?enable_pipeline=true'
  - 'tls://120.53.53.53?enable_pipeline=true'  
local_ip:
  - 'chnroutes.txt'
local_domain:
  - 'apple.china.conf.raw.txt'
  - 'accelerated-domains.china.conf.raw.txt'
local_latency: 30
remote_upstream:
  - 'tls://8.8.8.8?enable_pipeline=true'
  - 'tls://8.8.4.4?enable_pipeline=true'
  - 'tls://1.1.1.1?enable_pipeline=true'
  - 'tls://1.0.0.1?enable_pipeline=true'
  - 'https://8.8.8.8/dns-query?enable_http3=true'
  - 'https://8.8.4.4/dns-query?enable_http3=true'
