log:
  level: info
  production: false

plugins:
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./accelerated-domains.china.conf.raw.txt"
        - "./apple.china.conf.raw.txt"

  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "1.1.1.1"
          #- addr: "1.0.0.1"
        - addr: "8.8.8.8"
          #- addr: "8.8.4.4"

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "tls://1.12.12.12"
          enable_pipeline: true
        - addr: "tls://223.5.5.5"
          enable_pipeline: true
            #        - addr: "tls://120.53.53.53"
            #          enable_pipeline: true
            #        - addr: "tls://223.6.6.6"
            #          enable_pipeline: true

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
        #- exec: debug_print local_forward
      - exec: $local_forward

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
        #- exec: debug_print remote_forward
      - exec: $remote_forward

  - tag: "main_sequence"
    type: sequence
    args:
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - exec: goto remote_sequence

  - type: udp_server
    args:
      entry: main_sequence
      listen: :53
