server_addr: ":53"
#cache_size: 0
#lazy_cache_ttl: 0
#lazy_cache_reply_ttl: 0
#redis_cache: ""
#min_ttl: 0
#max_ttl: 0
#hosts: []
#arbitrary: []
blacklist_domain: [geosite.dat:category-ads-all]
#insecure: false
#ca: []
debug: true
#log_file: ""
#upstream: []
local_upstream: [https://223.5.5.5/dns-query]
local_ip: [geoip.dat:cn]
local_domain: [geosite.dat:cn,geosite.dat:category-games@cn]
local_latency: 50
remote_upstream: [https://8.8.8.8/dns-query,https://1.1.1.1/dns-query]
remote_domain: [geosite.dat:geolocation-!cn]
#working_dir: ""
#cd2exe: false
