log:
  level: debug
  file: ''
plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - main_sequence
#        - modify_ttl
      server:
        - protocol: udp
          addr: ':53'
        # - protocol: tcp
        #   addr: ':53'
#        - protocol: udp
#          addr: '[::1]:53'
#        - protocol: tcp
#          addr: '[::1]:53'
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _return
#        - mem_cache
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            # - ecs-local
            - forward_local
            - _return
        # - if:
        #     - query_is_non_local_domain
        #   exec:
        #     - _prefer_ipv4
        #     - forward_remote
        #     - _return
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            #- ecs-remote
            - _prefer_ipv4
            - forward_remote
          fast_fallback: 200
          always_standby: true
#  - tag: mem_cache
#    type: cache
#    args:
#      size: 1024
#  - tag: modify_ttl
#    type: ttl
#    args:
#      minimal_ttl: 300
#      maximum_ttl: 3600

  # - tag: ecs-local
  #   type: ecs
  #   args:
  #     auto: false #仅适用于公网的服务器。本地运行不要启用这个功能。
  #     ipv4: xxx # IPv4 curl -s https://v4.myip.la 
  #     # ipv6: ${{ curl -s https://v6.myip.la }} # IPv6 curl -s https://v6.myip.la
  #     force_overwrite: true # 强制覆盖
  #     mask4: 16 # 用于 ipv4 地址的掩码 默认: 24。
  #     # mask6: 48 # 用于 ipv6 地址的掩码 默认: 48。

  # - tag: ecs-remote
  #   type: ecs
  #   args:
  #     auto: true #仅适用于公网的服务器。本地运行不要启用这个功能。
  #     #ipv4: ${{ curl -s https://v4.myip.la }} # IPv4 curl -s https://v4.myip.la 
  #     # ipv6: ${{ curl -s https://v6.myip.la }} # IPv6 curl -s https://v6.myip.la
  #     force_overwrite: true # 强制覆盖
  #     #mask4: 16 # 用于 ipv4 地址的掩码 默认: 24。
  #     # mask6: 48 # 用于 ipv6 地址的掩码 默认: 48。

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
#        - addr: 'https://1.12.12.12/dns-query'
        - addr: 'tls://1.12.12.12'
          enable_pipeline: true
        - addr: 'tls://120.53.53.53'
          enable_pipeline: true  
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
#        - addr: 'https://1.1.1.1/dns-query'
        - addr: 'tls://8.8.8.8'
          enable_pipeline: true
        - addr: 'tls://8.8.4.4'
          enable_pipeline: true
        - addr: 'tls://1.1.1.1'
          enable_pipeline: true
        - addr: 'tls://1.0.0.1'
          enable_pipeline: true
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./accelerated-domains.china.conf.raw.txt'
        - 'ext:./apple.china.conf.raw.txt'
  # - tag: query_is_non_local_domain
  #   type: query_matcher
  #   args:
  #     domain:
  #       - 'ext:./geosite.dat:geolocation-!cn'
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./anti-ad-domains.txt'
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./chnroutes.txt'
