server_addr: ":53530"
#cache_size: 0
#lazy_cache_ttl: 0
#lazy_cache_reply_ttl: 0
#redis_cache: ""
#min_ttl: 0
#max_ttl: 0
#hosts: []
#arbitrary: []
blacklist_domain: [geosite.dat:category-ads-all]
#insecure: false
#ca: []
debug: true
#log_file: ""
#upstream: []
local_upstream: [https://dns.alidns.com/dns-query,https://doh.pub/dns-query]
local_ip: [geoip.dat:cn]
local_domain: [geosite.dat:cn]
local_latency: 50
remote_upstream: [https://dns.google/dns-query,https://cloudflare-dns.com/dns-query]
remote_domain: [geosite.dat:geolocation-!cn]
#working_dir: ""
#cd2exe: false
